### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by Volkor3-16** [triazo/immersive_scaler#12]
Running CATS dev build (the one with integration), but I don't think that's relevant.
I tried both the latest commit on master, and the release, and got the same error.
Happy to help out with debugging if needed :)

```python
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_operators\userpref.py", line 458, in execute
    mod = addon_utils.enable(self.module, default_set=True, handle_error=err_cb)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 305, in enable
    if mod and os.path.exists(mod.__file__):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

location: <unknown location>:-1
```

**Comment by Volkor3-16** [comment]
Same error on Blender LTS 2.93.8

**Comment by triazo** [comment]
Figured I'd comment since I've figured out what's going on here, I haven't figured out the best fix yet but there's probably a few ways I can do it and I'll try to get that up asap so I can release 0.3 and work on redoing stuff for ik2 and lock all mode.

So the cats integration uses a submodule, when you the whole repo as a zip (as all installations of the cats dev are) that submodule isn't populated and is just left as an empty folder, which is picked up by blender python as an empty module. When immersive scaler is installed later, python continues to use the old module until either the list is refreshed or blender is restarted. I basically need to force blender to reload the module list at some point.

Workaround for now is to install, restart blender, then enable.
