### ISSUE TITLE
Allow choosing the bone mapping from the addon UI.

### ISSUE THREAD

**Issue by CheesecakeCG** [triazo/immersive_scaler#4]
It would great if the addon let you pick which bones are which from the addon's UI instead of having to hardcode your bone names into the script. It would also be great if it did a fuzzy string match to autofill the bone names so you only have to correct the ones that are wrong.

**Comment by triazo** [comment]
I have this on my radar now, I need to find a way to do this cleanly in the UI without it being distracting for those who don't need it.

**Comment by Iconoclass** [comment]
I 100% second this. It's a feature I need for my Booth model specifically because changing the bone names would make it incredibly tedious to remap and fix all the toggles and animations in Unity.

I feel like one way you could add this option in the UI is just to make it a dropdown and clearly label it "(optional)". If there is no bone specified in the slot it just uses the hardcoded values. 

My bones' names follow the camelcase convention, like "RightLeg" instead of "right_leg". If you could hardcode variants like these that would be great too.

**Comment by triazo** [comment]
Implemented in [79579a7](https://github.com/triazo/immersive_scaler/commit/79579a7c04669eef10a2c2137b687c1680521b0e)
It'll be in the next release, probably in a couple  of days.
