### ISSUE TITLE
Model floor is set incorrectly when an object on the avatar is lower than the feet.

### ISSUE THREAD

**Issue by NotAKidoS** [triazo/immersive_scaler#8]
My model has a long tail that clips with the floor a tiny bit. After running the script, the tail is aligned with the floor, pushing the avatars feet up in the air. I would guess avatars with chains and other accessories run into the same issue.

One possible solution would be to set the avatars position to the ankle/foots position before scaling, so once it is scaled the avatar is roughly in the same spot.

**Comment by NotAKidoS** [comment]
A cheapo workaround I am using is to move the object up with a shapekey, apply to basis, run the script, then apply the reverted shapekey back to basis.

**Comment by triazo** [comment]
It was getting the bottom of the avatar based on the lowest point, I changed it so it'll get it based on the lowest point _weighted to the foot_
This doesn't cover every conceivable use case, but since the foot is scaled in the process and could be kinda tall on certian avatars with, say, high heels, I don't want to just fix a height for the ankle bone.
